### ISSUE TITLE
Multi-page form - Fatal error: Uncaught DOMException: Invalid Character Error

### ISSUE THREAD

**Issue by hy-itops** [WenderHost/gf-entry-xml-export#1]
Hi There,

When I create a multi-page form, I get the following error:

```
Fatal error: Uncaught exception 'DOMException' with message 'Invalid Character Error' in /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php:153 
Stack trace: #0 /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php(153): DOMDocument->createElement('') 
#1 /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php(110): GFtoXML\ArrayToXml\ArrayToXml->addNode(Object(DOMElement), '', '') 
#2 /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php(48): GFtoXML\ArrayToXml\ArrayToXml->convertElement(Object(DOMElement), Array) 
#3 /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php(62): GFtoXML\ArrayToXml\ArrayToXml->__construct(Array, 'form', true) 
#4 /wp-content/plugins/gf-entry-xml-export-master/lib/fns/gravityforms.php(153): GFtoXML\ArrayToXml\ArrayToXml::convert(Array, 'form') 
#5 [internal function]: GFtoXML\gravity in /wp-content/plugins/gf-entry-xml-export-master/lib/classes/array-to-xml.php on line 153
```

If I remove the page break the plugin works fine.
Love the plugin btw.

Cheers,
kp

**Comment by hy-itops** [comment]
Hi again,

Sorry, I didn't know if I should create a new Issue or not.
I would also like to change the structure of the XML that gets generated.
I would like to wrap some elements around come elements created by the form.
The kind of structure I am hoping to get is as follows:

<OnlineImportApplications>
     <Application> -> Hard coded elements
           <time></time>  -> Created by form
           <sequence></sequence>  -> Created by form
     </Application> -> Hard coded elements
     <Contact> -> Hard coded elements
           <surname></surname>  -> Created by form
           <first_name></first_name>  -> Created by form
          <gender></gender>  -> Created by form
          <email></email>  -> Created by form
          <phone></phone>  -> Created by form
          <address></address>  -> Created by form
     </Contact> -> Hard coded elements
</OnlineImportApplications>

I hope that makes sense.
Thanks in advance for you help.

Cheers,
kp

**Comment by Raesgo** [comment]
Hey there,
Great plugin!

I am getting that Fatal Error as well when I have a multi step form.
Any chance anyone knows any tips on getting the xml results with a multi step form?

Thanks

**Comment by Malenko123** [comment]
Any news on this? I'm having the same problem
